spring:
  application:
    name: lolien-discord-bot
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver

config:
  file:
    path:
      windows: C:\config-%s.json
      linux: /usr/local/tomcat/conf/config-%s.json

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC

management:
  endpoints:
    web:
      base-path: /application
      path-mapping:
        health: healthcheck